### ISSUE TITLE
Events not firing on OSX El Capitan (10.11.1)

### ISSUE THREAD

**Issue by bruce** [CargoSense/usb-driver#17]

**Comment by lrz** [comment]
Maybe related to the new security system. I will investigate.

**Comment by bruce** [comment]
`getAll()` appears to be _mostly_ working (see #18) -- but no `mount` info.

**Comment by bruce** [comment]
Events are now firing, but the `mount` event is missing a `mount` device object value.

![developer_tools](https://cloud.githubusercontent.com/assets/72/10901243/15b8cfcc-81a0-11e5-802f-624de44c472b.png)
